export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_INVOICES = "LOAD_INVOICES";
export const LOAD_INVOICES_SUCCESS = "LOAD_INVOICES_SUCCESS";
